# Generated by Django 5.2.3 on 2025-07-01 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(help_text='Ex: Rua, Avenida, Travessa', max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=50, null=True)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('pais', models.CharField(default='Brasil', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Ex: (99) 99999-9999', max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('ARQUIVADO', 'Arquivado')], default='ATIVO', max_length=10)),
                ('enderecos', models.ManyToManyField(blank=True, to='clientes.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteTelefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RESIDENCIAL', 'Residencial'), ('COMERCIAL', 'Comercial'), ('CELULAR', 'Celular'), ('OUTRO', 'Outro')], default='CELULAR', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('telefone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.telefone')),
            ],
            options={
                'unique_together': {('cliente', 'telefone')},
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefones',
            field=models.ManyToManyField(blank=True, through='clientes.ClienteTelefone', to='clientes.telefone'),
        ),
    ]
