# Generated by Django 5.2.3 on 2025-07-15 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='logradouro',
            new_name='logadouro',
        ),
    ]
